name: Auto query

on:
  schedule:
    - cron: '* 3 * * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'Auto query'
        type: boolean
        required: true
        default: true

jobs:
  Invoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 'Install dependencies'
        run: python -m pip install astrapy

      - name: Run
        env:
          id: ${{ secrets.ID }}
          region: ${{ secrets.REGION }}
          token: ${{ secrets.TOKEN }}
          keyspace: ${{ secrets.KEYSPACE }}
        run: python main.py
